version: "3"
services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://app-backend:3000

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
