name: Run Backend Temporarily

on:
  workflow_dispatch: # Permette l'avvio manuale per test

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: |
          cd backend
          npm start
        timeout-minutes: 60 # Tempo massimo di esecuzione del backend
