name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Front folder
      run: cd frontend

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build -- --output-path=dist --base-href="/DiegoFCJPortfolio/frontend"

    - name: Move files to root for GitHub Pages
      run: |
        mv dist/browser/* dist/
        rm -r dist/browser

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
        clean: true