name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'  # Trigger solo su tag che iniziano con "v"

permissions:
  contents: write  # Necessario per permettere il push su GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Usa una versione LTS

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build -- --output-path=dist --base-href="/DiegoFCJPortfolio/"

    # Step per spostare i file dalla cartella `browser` alla root di `dist`
    - name: Move files to root for GitHub Pages
      run: |
        mv dist/browser/* dist/
        rm -r dist/browser

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages           # Branch di destinazione per GitHub Pages
        folder: dist                # Cartella di output del build
        clean: true                 # Opzionale: pulisce il contenuto di `gh-pages` prima del deploy
