name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build -- --output-path=dist/diego-fcjportfolio

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/diego-fcjportfolio
