name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch: # Trigger manuale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Iniettare variabile API_KEY_GITHUB in environment.prod.ts
        run: |
          sed -i 's/githubToken: ""/githubToken: "${{ secrets.API_KEY_GITHUB }}"/' src/environments/environment.prod.ts

      - name: Build Project
        run: npm run build -- --output-path=frontend/dist --base-href="/DiegoFCJPortfolio/"

      - name: Move Files to Root for GitHub Pages
        run: |
          mv /dist/diego-fcjporfolio/* /dist/
          rm -r /dist/diego-fcjporfolio

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: /dist
          clean: true
