name: Deploy Backend and Frontend

on:
  # Triggered by push with version tags (for frontend deploy) or by manual dispatch (for backend testing)
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows for manual dispatch of this workflow

permissions:
  contents: write

jobs:
  # Job to run the backend temporarily
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend

      - name: Start Backend
        run: npm start
        working-directory: backend
        # Keeps the backend running for a limited time or as needed
        timeout-minutes: 60 # Set the time the backend will stay active

  # Job to build and deploy the frontend
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: run-backend # Ensures this job runs after backend job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend Project
        run: npm run build -- --output-path=dist --base-href="/DiegoFCJPortfolio/"
        working-directory: frontend

      - name: Move Files to Root for GitHub Pages
        run: |
          mv frontend/dist/browser/* frontend/dist/
          rm -r frontend/dist/browser

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist
          clean: true
