name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:   
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          npm run build -- --output-path=dist --base-href="/DiegoFCJPortfolio/"

      # Step di diagnostica per mostrare il contenuto della cartella dist
      - name: Check Dist Directory
        run: |
          ls -R dist

      # Controllo e spostamento condizionale dei file in dist/
      - name: Move Files to Root for GitHub Pages
        run: |
          if [ -d "dist/diego-fcjportfolio" ]; then
            mv dist/diego-fcjportfolio/* dist/
            rm -r dist/diego-fcjportfolio
          elif [ -d "dist/DiegoFCJPortfolio" ]; then
            mv dist/DiegoFCJPortfolio/* dist/
            rm -r dist/DiegoFCJPortfolio
          else
            echo "No subfolder found to move."
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/
          clean: true
