name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build -- --output-path=dist/diego-fcjportfolio

      - name: Verify Build Output
        run: ls dist/diego-fcjportfolio

      - name: Copy index.html to 404.html
        run: cp dist/diego-fcjportfolio/index.html dist/diego-fcjportfolio/404.html

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/diego-fcjportfolio
