name: Run Backend Temporarily

on:
  workflow_dispatch: # Permette di avviare il server manualmente

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run backend
        run: |
          cd backend
          npm start
        timeout-minutes: 60
